apiVersion: v1
kind: Namespace
metadata:
  name: fuse-system
  labels:
    name: fuse-system
    # Enable Cilium network policies
    cilium.io/policy-enforcement: enabled
    # Enable Hubble observability
    hubble.io/observe: "true"
